---
# COMP90024 Cloud Computing Project 2
# Team 40:
# Mark Drvodelic 1068574
# Colton Carner 693280
# Bing Xu 833684
# Zihao Zhang 1151006
# Brandon Lulham 1162377

# saves a lists of IPs for the MRC instances
# see thes script files for more info

- name: run the scripts to get IPs and configure couchDB
  shell: python3 ./inventory/01-openstack_inventory.py --list | python3 ./configuration_scripts/hosts_ip_string.py > ./openstack-ips.txt