---
# COMP90024 Cloud Computing Project 2
# Team 40:
# Mark Drvodelic 1068574
# Colton Carner 693280
# Bing Xu 833684
# Zihao Zhang 1151006
# Brandon Lulham 1162377

# Install dependencies on the deployment machine to be able to execute ansible
# scripts and interface with openstack

#sudo apt-get update; sudo apt-get install python-pip
- name: Install Pip
  become: yes
  apt:
    name: ["python3-pip"]
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

#pip install --upgrade pip
- name: Update pip
  pip:
    name: "pip"
    state: latest

#pip install openstack sdk
- name: Install openstacksdk
  pip:
    name: "openstacksdk"
    state: latest
    extra_args: --ignore-installed PyYAML #issue with uninstalling PyYAML https://github.com/conan-io/conan/issues/5094
