---
# COMP90024 Cloud Computing Project 2
# Team 40:
# Mark Drvodelic 1068574
# Colton Carner 693280
# Bing Xu 833684
# Zihao Zhang 1151006
# Brandon Lulham 1162377

#show all available Openstack images
- name: Retrieve all available openstack images
  os_image_info:
  register: image_result #save results to var called 'image_result'

- name: Show openstack image information
  debug:
    msg: "{{ image_result.openstack_image }}"
