---
#show all available Openstack images
- name: Retrieve all available openstack images
  os_image_info:
  register: image_result #save results to var called 'image_result'

- name: Show openstack image information
  debug:
    msg: "{{ image_result.openstack_image }}"
