---
# COMP90024 Cloud Computing Project 2
# Team 40:
# Mark Drvodelic 1068574
# Colton Carner 693280
# Bing Xu 833684
# Zihao Zhang 1151006
# Brandon Lulham 1162377

- name: Delete existing 'cloudssh' public key from Openstack
  os_keypair:
      state: absent
      name: cloudssh

- name: Upload new publickey to Openstack
  os_keypair:
      state: present
      name: cloudssh
      public_key_file: ./secrets/publickey.pem
