---
# COMP90024 Cloud Computing Project 2
# Team 40:
# Mark Drvodelic 1068574
# Colton Carner 693280
# Bing Xu 833684
# Zihao Zhang 1151006
# Brandon Lulham 1162377

#Create an instance on MRC
- name: create an instance
  os_server:
    name: "{{item.name}}"
    image: "{{instance_image}}"
    key_name: "{{instance_key_name}}"
    flavor: "{{item.flavor}}"
    availability_zone: "{{availability_zone}}"
    security_groups: "{{sg_names}}"
    volumes: "{{item.volumes}}" #automatically associates with the volume
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  loop: "{{instances}}"
  register: os_instance

- debug:
    msg: "Instance {{item.openstack.name}} has been created. IP address is {{item.openstack.public_v4}}"
  loop: "{{os_instance.results}}"
  when: item.openstack is defined

#Need to make sure that we can connect via SSH (since sometimes there is some config
# that happens on cloud even after instance marked 'ready', and next task requires SSH)
#NOTE: removed this, because it sometimes was failing the pipeline... replaced with a wait timer

# - name: Wait for connection
#   wait_for:
#     host: "{{item.openstack.public_v4}}"
#     port: 22
#     timeout: 120
#     search_regex: OpenSSH
#   loop: "{{os_instance.results}}"
#   when: item.openstack is defined

- name: stop and wait for deployment to finalise before continuing.
  pause:
    minutes: 1


#add hosts to in memory inventory so we can refer to them in later scripts
- name: add hosts
  add_host:
    name: '{{item.openstack.public_v4}}'
    groups: COMP90024-all
  loop: '{{ os_instance.results }}'
  when: item.openstack is defined


# add the main/control node to its own group to the inmemory inventory
- name: add main host
  add_host:
    name: '{{ os_instance.results[0].openstack.public_v4 }}'
    group: COMP90024-main

