---
    
#start up docker
- name: Run docker Daemon
  become: yes
  service: 
    name: docker
    state: started
  become: true

#install our frontend container
- name: pull docker container
  become: yes
  docker_image:   
   name: couchdb
   tag: latest

- name: frontend docker install
  become: yes
  docker_container:
    name: couchdb
    image: couchdb
    state: started
    recreate: yes
    published_ports: # as per https://docs.couchdb.org/en/stable/setup/cluster.html
      - "80:3000"

- name: stop and wait for docker deployment
  pause:
    minutes: 1




