---
    
#start up docker
- name: Run docker Daemon
  become: yes
  service: 
    name: docker
    state: started

#install our frontend container
- name: pull docker container
  become: yes
  docker_image: 
   source: pull  
   name: coltonc/comp90024_frontend
   force_source: yes 
   tag: latest

- name: frontend docker install
  become: yes
  docker_container:
    name: frontend
    image: coltonc/comp90024_frontend
    state: started
    recreate: yes
    published_ports:
      - "80:3000"

- name: stop and wait for docker deployment
  pause:
    minutes: 1




