---
# COMP90024 Cloud Computing Project 2
# Team 40:
# Mark Drvodelic 1068574
# Colton Carner 693280
# Bing Xu 833684
# Zihao Zhang 1151006
# Brandon Lulham 1162377

#start up docker
- name: Run docker Daemon
  become: yes
  service: 
    name: docker
    state: started

#install our frontend container
- name: pull docker container
  become: yes
  docker_image: 
   source: pull
   force_source: yes   
   name: coltonc/comp90024_frontend
   tag: latest

- name: frontend docker install
  become: yes
  docker_container:
    name: frontend
    image: coltonc/comp90024_frontend
    state: started
    recreate: yes
    published_ports:
      - "80:3000"

- name: stop and wait for docker deployment
  pause:
    minutes: 1




