---
# COMP90024 Cloud Computing Project 2
# Team 40:
# Mark Drvodelic 1068574
# Colton Carner 693280
# Bing Xu 833684
# Zihao Zhang 1151006
# Brandon Lulham 1162377

#on the main/coordination host, setup the Couch cluster
- hosts: instance-1
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true
  remote_user: ubuntu
  environment:
      COUCHDB_USER: '{{ couch_db_username }}'
      COUCHDB_PASSWORD: '{{ couch_db_password }}'
      COUCHDB_SECRET: '{{ couch_db_secret }}'
      ERL_FLAGS: "-setcookie {{ couch_db_secret }} -name couchdb@{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }} -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9105"
  roles:
    - couchdb-clustering