---
- hosts: localhost
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    # - role: openstack-common #just for setting up the local computer to run ansible
    - role: openstack-upload-publickey