---
#Install couchdb for ALL hosts
- hosts: all
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true
  remote_user: ubuntu
  roles:
    - role: openstack-mount-volumes-filesystem
    - role: proxy-config
    - role: docker-install #temp comment out to speed up testing couchdb install/config
  
    
  