---

#then on the main/coordination host, setup the cluster
- hosts: instance-1
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true
  remote_user: ubuntu
  environment:
      COUCHDB_USER: '{{ couch_db_username }}'
      COUCHDB_PASSWORD: '{{ couch_db_password }}'
      COUCHDB_SECRET: '{{ couch_db_secret }}'
      ERL_FLAGS: "-setcookie {{ couch_db_secret }} -name couchdb@{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }} -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9105"
  roles:
    - couchdb-clustering