---
# COMP90024 Cloud Computing Project 2
# Team 40:
# Mark Drvodelic 1068574
# Colton Carner 693280
# Bing Xu 833684
# Zihao Zhang 1151006
# Brandon Lulham 1162377

- hosts: instance-1
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true
  remote_user: ubuntu
  roles:
    - role: frontend-start-docker-container