---
# COMP90024 Cloud Computing Project 2
# Team 40:
# Mark Drvodelic 1068574
# Colton Carner 693280
# Bing Xu 833684
# Zihao Zhang 1151006
# Brandon Lulham 1162377

# Run all scripts
- import_playbook: mrc-openstack-configure.yaml
- import_playbook: mrc-install.yaml
- import_playbook: mrc-start-couchdb.yaml
- import_playbook: mrc-cluster-couchdb.yaml
- import_playbook: mrc-python-execute.yaml
- import_playbook: mrc-start-frontend.yaml

