---
# COMP90024 Cloud Computing Project 2
# Team 40:
# Mark Drvodelic 1068574
# Colton Carner 693280
# Bing Xu 833684
# Zihao Zhang 1151006
# Brandon Lulham 1162377

- name: Give the volume a file system
  become: yes
  filesystem:
    fstype: ext4
    dev: "{{ volume_device }}"

- name: Create the directory to serve as mounting point
  become: yes
  file:
    path: "{{ volume_mount_point }}"
    state: directory

- name: Mount the volume
  become: yes
  mount:
    path: "{{ volume_mount_point }}"
    src: "{{ volume_device }}"
    fstype: ext4
    state: mounted